---
exclude: "dockerfiles|ci_build_images/qpress|cross-reference/crossreference/cr/static/cr/font-awesome"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        name: check yaml files
      - id: debug-statements
        name: check for Python debug statements
      - id: trailing-whitespace
        name: check trailing whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
            (?x)^(
              master-web/templates/home.jade
            )$
  # - repo: https://gitlab.com/pycqa/flake8.git
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       name: check python (flake8)
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: check yaml files (yamllint)
  - repo: https://github.com/fauust/pre-commit-shell
    rev: v1.1
    hooks:
      - id: shellcheck
        name: check shell script (shellcheck)
        args: ["-x"]
      # - id: shfmt
      #   name: check shell style (shfmt)
      #   args: ["-d", "-i", "2", "-ci"]
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        name: check for markdown lint (mdl)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: check for common misspellings in text files
        entry: codespell
        language: python
  - repo: https://github.com/PyCQA/pylint.git
    rev: v3.1.0
    hooks:
      - id: pylint
        name: check python syntax (pylint)
        entry: pylint
        language: system
        types: [file]
        files: \.(cfg|py|tac)$
        # TODO add cross-reference in the future
        # exclude: ^cross-reference/.*$
        args:
          [
            "--errors-only",
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Config file
            "--disable=django-not-configured", # Silence django warning
          ]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: check python formating (black)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        name: check python syntax (pyupgrade)
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: check python imports order (isort)
        args: ["--profile", "black", "--filter-files"]
  - repo: local
    hooks:
      - id: docker-hadolint
        name: Run hadolint with docker
        language: docker_image
        entry: hadolint/hadolint:latest hadolint
        files: Dockerfile
