---
version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: buildbot
      MARIADB_USER: buildmaster
      MARIADB_PASSWORD: password

  master-web:
    image: quay.io/mariadb-foundation/bb-master:master-web
    restart: unless-stopped
    volumes:
      - /srv/buildbot/log:/var/log/buildbot
      - ./start-bbm-web.sh:/usr/local/bin/start-bbm-web.sh
    entrypoint:
      - /usr/local/bin/start-bbm-web.sh
    ports:
      - "127.0.0.1:8010:8010"
    depends_on:
      - mariadb
