#!/usr/bin/env python3

master_directories = [
    "autogen/aarch64-master-0",
    "autogen/amd64-master-0",
    "autogen/amd64-master-1",
    "autogen/ppc64le-master-0",
    "autogen/s390x-master-0",
    "autogen/x86-master-0",
    "master-docker-nonstandard",
    "master-galera",
# TODO Enable these once it's more clear what needs to be done
#    "master-libvirt",
#    "master-nonlatent",
    "master-protected-branches",
]

start_template = """
---
version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=buildbot
      - MARIADB_USER=buildmaster
      - MARIADB_PASSWORD=password
    networks:
      net_back:
    healthcheck:
      test: ['CMD', "mariadb-admin", "--password=password", "--protocol", "tcp", "ping"]
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - ./mariadb:/var/lib/mysql:rw
    # command: --tmpdir=/var/lib/mysql/tmp

  crossbar:
    image: crossbario/crossbar
    restart: unless-stopped
    container_name: crossbar
    networks:
      net_back:

  master-web:
    image: quay.io/mariadb-foundation/bb-master:master-web
    restart: unless-stopped
    container_name: master-web
    volumes:
      - ./logs:/var/log/buildbot
      - ./buildbot/:/srv/buildbot/master
    entrypoint:
      - /srv/buildbot/master/docker-compose/start-bbm-web.sh
    networks:
      net_front:
      net_back:
    ports:
      - "127.0.0.1:8010:8010"
    depends_on:
      - mariadb
      - crossbar
"""

docker_compose_template = """
  {master_name}:
    image: quay.io/mariadb-foundation/bb-master:master
    restart: unless-stopped
    container_name: {master_name}
    volumes:
      - ./logs:/var/log/buildbot
      - ./buildbot/:/srv/buildbot/master
    entrypoint:
      - /bin/bash
      - -c
      - "/srv/buildbot/master/docker-compose/start.sh {master_directory}"
    networks:
      net_front:
      net_back:
    ports:
      - "127.0.0.1:{port}:{port}"
    depends_on:
      - mariadb
      - crossbar
"""

end_template = """
networks:
  net_front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/24
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "br_bb_front"
  net_back:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.201.0/24
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "br_bb_back"
"""

# Generate startup scripts and Docker Compose pieces for each master directory
with open("docker-compose.yaml", "w") as f:
    f.write("# This is an autogenerated file. Do not edit it manually. Use `python generate-config.py` instead.")
    f.write(start_template)
    port = 8011
    for master_directory in master_directories:
        master_name = master_directory.replace("/", "_")

        # Generate Docker Compose piece
        docker_compose_piece = docker_compose_template.format(
            master_name=master_name,
            master_directory=master_directory,
            port=port,
        )
        port += 1

        f.write(docker_compose_piece)
    f.write(end_template)
