---
services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_BROWSER_REDIRECT_URL=https://minio.mariadb.org/minio/ui/
      - MC_HOST_local=http://localhost:8080
    network_mode: host
    command: server /data --console-address  ":8081" --address :8080
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /data/minio/:/data
    logging:
      driver: journald
      options:
        tag: "minio"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/ssl/:/etc/nginx/ssl/:ro
    network_mode: host
    logging:
      driver: journald
      options:
        tag: "minio-nginx"
