name: Build SLES:pip based images

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'ci_build_images/sles.Dockerfile'
      - 'ci_build_images/pip.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - 'ci_build_images/mariadb_zypper_expect'
      - .github/workflows/build-sles.pip-based.yml
      - .github/workflows/bbw_build_container_template.yml
  pull_request:
    paths:
      - 'ci_build_images/sles.Dockerfile'
      - 'ci_build_images/pip.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - 'ci_build_images/mariadb_zypper_expect'
      - .github/workflows/build-sles.pip-based.yml
      - .github/workflows/bbw_build_container_template.yml

  workflow_call:

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: registry.suse.com/bci/bci-base:15.6
            platforms: linux/amd64, linux/s390x
            tag: sles1506
            nogalera: false

          - image: registry.suse.com/bci/bci-base:15.7
            platforms: linux/amd64, linux/s390x
            tag: sles1507
            nogalera: false

    uses: ./.github/workflows/bbw_build_container_template.yml
    with:
      dockerfile: sles.Dockerfile pip.Dockerfile
      image: ${{ matrix.image }}
      platforms: ${{ matrix.platforms }}
      tag: ${{ matrix.tag }}
      nogalera: ${{ matrix.nogalera }}
      files:
        '[
          {"name": "mariadb_zypper_expect", "source": "''$WORKDIR/mariadb_zypper_expect''", "target": "''$GITHUB_WORKSPACE''"}
        ]'
    secrets: inherit
