name: Build Debian:msan based images

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'ci_build_images/debian.Dockerfile'
      - 'ci_build_images/msan.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - .github/workflows/build-debian.msan-based.yml
      - .github/workflows/bbw_build_container_template.yml
  pull_request:
    paths:
      - 'ci_build_images/debian.Dockerfile'
      - 'ci_build_images/msan.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - .github/workflows/build-debian.msan-based.yml
      - .github/workflows/bbw_build_container_template.yml
  workflow_call:

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: debian:11
            platforms: linux/amd64
            branch: 10.11
            tag: debian11-msan
            clang_version: 15
            nogalera: false

          - image: debian:11
            platforms: linux/amd64
            branch: 10.11
            tag: debian11-msan-clang-16
            clang_version: 16
            nogalera: false

    uses: ./.github/workflows/bbw_build_container_template.yml
    with:
      dockerfile: debian.Dockerfile msan.Dockerfile
      image: ${{ matrix.image }}
      platforms: ${{ matrix.platforms }}
      tag: ${{ matrix.tag }}
      branch: ${{ matrix.branch }}
      clang_version: ${{ matrix.clang_version }}
      nogalera: ${{ matrix.nogalera }}
    secrets: inherit
