name: Build Debian:jepsen based images

on:
  push:
    paths:
      - 'ci_build_images/debian.Dockerfile'
      - 'ci_build_images/jepsen-mariadb.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - .github/workflows/build-debian.jepsen-based.yml
      - .github/workflows/bbw_build_container_template.yml
  pull_request:
    paths:
      - 'ci_build_images/debian.Dockerfile'
      - 'ci_build_images/jepsen-mariadb.Dockerfile'
      - 'ci_build_images/qpress.Dockerfile'
      - 'ci_build_images/buildbot-worker.Dockerfile'
      - .github/workflows/build-debian.jepsen-based.yml
      - .github/workflows/bbw_build_container_template.yml
  workflow_call:

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu:22.04
            platforms: linux/amd64
            branch: 10.11
            tag: ubuntu22.04-jepsen-mariadb
    uses: ./.github/workflows/bbw_build_container_template.yml
    with:
      dockerfile: debian.Dockerfile jepsen-mariadb.Dockerfile
      image: ${{ matrix.image }}
      platforms: ${{ matrix.platforms }}
      tag: ${{ matrix.tag }}
      branch: ${{ matrix.branch }}
    secrets: inherit
