---
name: unittests

on:
  pull_request:
    paths:
      - configuration/**
  push:
    paths:
      - configuration/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      #//TEMP we need to check only modified files WRT main
      - name: Install requirements (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Install requirements (uv pip)
        run: |
          python_version=$(python3 --version 2>&1 | awk '{print $2}' | cut -d. -f1,2)
          curl -LsSf https://astral.sh/uv/install.sh | sh
          make UV_PYTHON=$python_version venv
          make UV_PYTHON=$python_version install
      - name: Run unit tests
        run: |
          source .venv/bin/activate
          make test
