---
name: unittests

on:
  pull_request:
  push:

jobs:
  unittests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      #//TEMP we need to check only modified files WRT main
      - name: Install requirements (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev
      - name: Install requirements (uv pip)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          make venv
          make install
      - name: Run unit tests
        run: |
          source .venv/bin/activate
          make test
